### PR TITLE
add custom hooks

### PR DESCRIPTION
**Pull request by b4ldr**
I just migrated from using spuder/puppet-gitlab module to this on and found that there was no support for custom hooks.  this pull request adds spuder/puppet-gitlab/manifest/custom_hooks.pp to this project

### CODE REVIEW

**Comment by b4ldr** [comment]
Not sure why test are failing the all pass when run locally

**Comment by petems** [comment]
@b4ldr Tests are failing in travis due to strict variable setting, fixed in https://github.com/vshn/puppet-gitlab/pull/57

**Comment by b4ldr** [comment]
thanks @petems, ill wait for that to #57 to get merged then

**Comment by tobru** [comment]
@b4ldr as #57 has been merged, would you mind rebasing this PR and make sure that the Travis checks pass?

**Comment by b4ldr** [comment]
done

**Comment by tobru** [comment]
Looks good so far. I would really appreciate if you could add this new feature to the README, so that everyone gets aware of it. Thanks

**Pull request merged**
