### PR TITLE
Add backup job

### PR DESCRIPTION
**Pull request by b4ldr**
Small pull to add managing the gitlab backup cron job

### CODE REVIEW

**Comment by LongLiveCHIEF** [comment]
This one has been on my list also, but I think it needs some things before it can be merged. Mainly, removing hardcoded values in favor of parameters.

**Comment by b4ldr** [comment]
@LongLiveCHIEF have updated with params for minute and hour.  i also added a param for the gitlab-rake bin although this should not really change.  I dont think this needs any further paramertisation but feel free to suggest some

**Comment by LongLiveCHIEF** [comment]
Those were the ones I was worried about in order to make it a good PR.  If you _really_ wanted bonus points, you could add SKIP's.  LGTM as is though.

**Comment by LongLiveCHIEF** [comment]
Unfortunately the addition will cause a broken command syntax. Skips need
to be in a very specific unspaced, comma-sepatated format, and this prints
them out as an array.

The quick win here would be just to change the attribute type to a string
and allow entry of whatever is passed in, leaving it up to the implementer
to pass a valid value for skips.

The other option would be to have a parameter called other_args and just
append that to the backup cron.

**Comment by b4ldr** [comment]
@LongLiveCHIEF you may have missed the join (https://github.com/vshn/puppet-gitlab/pull/155/files#diff-0ac866172efd29d0ddc2aa75ae6f182dR81) although it was joining them on white space before so i have fixed that to a comma

**Comment by b4ldr** [comment]
Further to this the reason i prefer an array over a string is for data validation when we move to puppet4.  at that point we can do something like

# types/skip.pp
```puppet
type Gitlab::Skip = Enum['db', 'uploads', 'repositories', 'builds', 'artifacts', 'lfs', 'registry', 'pages']
```


# manifests/init.pp
```puppet
class gitlab {
 ...
 Array[Gitlab::Skip] $backup_cron_skips
 ...
}

**Comment by LongLiveCHIEF** [comment]
Yeah, missed that. And speaking of skips... Puppet 5? Lol

**Comment by b4ldr** [comment]
anything preventing this?

**Comment by tobru** [comment]
Thanks

**Pull request merged**
