### PR TITLE
Add Beaker Travis acceptance tests

### LINKED ISSUE #88: Add Beaker acceptance tests
Add beaker acceptance tests to Travis

Basic tests to make sure standard install works 👍

### PR DESCRIPTION
**Pull request by petems**
Closes #88

### CODE REVIEW

**Comment by tobru** [comment]
Thanks a lot @petems for your effort here. Some checks are failing at the moment, maybe you have a chance to look into them? Seems to be Travis related, or some version incompatibilities...

**Comment by petems** [comment]
@tobru Funnily enough the timeout failure is an exposure of a live bug (see #90).

I might stick to just testing Ubuntu 14.04 for now, then expand out to other OS's as stuff is fixed.

**Comment by tobru** [comment]
I'll merge this now and see how it goes...

**Comment by tobru** [comment]
Tests are still failing - Not sure because of Beaker or because of a real problem. Therefore added the test to `allow_failures`

**Comment by petems** [comment]
Yep, I've got a fix for one of them, the other might be a live bug with the docker module, I'm running tests now 👍

**Pull request merged**
